##
#
# Standard CMake Module which can be used by FIND_PACKAGE functionality.
#
# Supported components:
# - DEFAULTS
#
# [Module init workflow]
# - include all CMDEF modules
#

CMAKE_MINIMUM_REQUIRED(VERSION 3.22 FATAL_ERROR)

SET(CMDEF_PACKAGE_NAME "CMDEF")

SET(${CMDEF_PACKAGE_NAME}_FOUND 1)
SET(${CMDEF_PACKAGE_NAME}_DIR "${CMAKE_CURRENT_LIST_DIR}")

INCLUDE_GUARD(GLOBAL)

FIND_PACKAGE(CMLIB REQUIRED COMPONENTS CMUTIL)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_ADD_LIBRARY.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_ADD_EXECUTABLE.cmake)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_COMPILE_OPTION.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_COMPILE_DEFINITION.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_LINK_OPTION.cmake)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_INSTALL.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_PACKAGE.cmake)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_HELPER.cmake)

