##
#
# Standard CMake Module which can be used by FIND_PACKAGE functionality.
#
# Supported components:
# - DEFAULTS
#
# [Module init workflow]
# - include all CMDEF modules
#

CMAKE_MINIMUM_REQUIRED(VERSION 3.16 FATAL_ERROR)

IF(DEFINED CMDEF_INCLUDED)
	_CMLIB_LIBRARY_DEBUG_MESSAGE("CMDEF Library already included")
	RETURN()
ENDIF()

# Flag that CMDEF is already included
SET(CMDEF_INCLUDED "1")

SET(CMDEF_PACKAGE_NAME "CMDEF")

FIND_PACKAGE(CMLIB COMPONENTS UTIL)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_ADD_LIBRARY.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_ADD_EXECUTABLE.cmake)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_COMPILE_OPTION.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_COMPILE_DEFINITION.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_LINK_OPTION.cmake)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_INSTALL.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/system_modules/CMDEF_PACKAGE.cmake)

SET(${CMDEF_PACKAGE_NAME}_FOUND 1)
SET(${CMDEF_PACKAGE_NAME}_DIR "${CMAKE_CURRENT_LIST_DIR}")

