# Multiple include sources configuration for CMDEF_ADD_LIBRARY tests

SET(MULTIPLE_INCLUDE_RESOURCES_DIR "${CMAKE_CURRENT_LIST_DIR}")

SET(LIBRARY_SOURCE_FILE "${MULTIPLE_INCLUDE_RESOURCES_DIR}/src/library.cpp")
SET(UTILS_SOURCE_FILE "${MULTIPLE_INCLUDE_RESOURCES_DIR}/src/utils.cpp")

SET(LIBRARY_INCLUDE_DIR "${MULTIPLE_INCLUDE_RESOURCES_DIR}/include")
SET(LIBRARY_INCLUDE1_DIR "${MULTIPLE_INCLUDE_RESOURCES_DIR}/include1")
SET(LIBRARY_INCLUDE2_DIR "${MULTIPLE_INCLUDE_RESOURCES_DIR}/include2")
