name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  
jobs:
  test_linux:
    strategy:
      matrix:
        image: [
          "test_debian:bullseye",
          "test_debian:bookworm",
          "test_ubuntu:2004",
          "test_ubuntu:2204",
          "test_ubuntu:2404",
          "test_fedora:41",
          "test_fedora:42"
          ]

    runs-on: ubuntu-latest
    container:
        image: ghcr.io/cmakelib/${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: |
            git config --global --add safe.directory "$(pwd)"
            git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
            git clone https://github.com/cmakelib/cmakelib.git
            export CMLIB_DIR=$(pwd)/cmakelib
            cd test/ && cmake .
 
  test_macos_11:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: |
            git config --global --add safe.directory "$(pwd)"
            git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
            git clone https://github.com/cmakelib/cmakelib.git
            export CMLIB_DIR=$(pwd)/cmakelib
            cd test/ && cmake .
