name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  CMLIB_VERSION: 1.2.0
  
jobs:
  test_linux:
    strategy:
      matrix:
        image: [
          "test_debian:bullseye",
          "test_debian:trixie",
          "test_debian:bookworm",
          "test_ubuntu:2004",
          "test_ubuntu:2204",
          "test_ubuntu:2404",
          "test_fedora:41",
          "test_fedora:42"
          ]

    runs-on: ubuntu-latest
    container:
        image: ghcr.io/cmakelib/${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: |
            git config --global --add safe.directory "$(pwd)"
            git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
            git clone --branch "v${CMLIB_VERSION}" https://github.com/cmakelib/cmakelib.git
            export CMLIB_DIR=$(pwd)/cmakelib
            cd test/ && cmake .
 
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: |
            git config --global --add safe.directory "$(pwd)"
            git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
            git clone --branch "v${CMLIB_VERSION}" https://github.com/cmakelib/cmakelib.git
            export CMLIB_DIR=$(pwd)/cmakelib
            cd test/ && cmake .

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: |
            git config --global --add safe.directory "$(pwd)"
            git remote set-url origin "${{ github.server_url }}/${{ github.repository }}"
            git clone --branch "v$Env:CMLIB_VERSION" https://github.com/cmakelib/cmakelib.git
            $Env:CMLIB_DIR=$(Join-Path -Path $(Get-Location).Path -ChildPath "cmakelib")
            cd test/ && cmake .